import { useMemo, useState } from "react";
import { ArrowLeft, ArrowUpRight, Bookmark, Check, ChevronRight, CircleAlert, ExternalLink, GitCompareArrows, Info, Share2, Sparkles } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import { AutoVistaLayout } from "@/components/AutoVistaLayout";
import { ExplodedViewer } from "@/components/ExplodedViewer";
import { VehicleCard } from "@/components/VehicleCard";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";

const categories = ["All systems", "Performance", "Chassis", "Dimensions", "Energy", "Technology"];

export default function CarDetail() {
  const [, params] = useRoute("/cars/:slug");
  const [, setLocation] = useLocation();
  const slug = params?.slug ?? "";
  const { data: car, isLoading } = trpc.catalog.bySlug.useQuery({ slug });
  const { data: related = [] } = trpc.catalog.related.useQuery({ slug });
  const { isAuthenticated } = useAuth();
  const toggleFavorite = trpc.favorites.toggle.useMutation();
  const [saved, setSaved] = useState(false);
  const [category, setCategory] = useState("All systems");
  const [compare, setCompare] = useState(() => { try { return JSON.parse(localStorage.getItem("autovista-compare") ?? "[]") as string[]; } catch { return []; } });
  const filteredSpecs = useMemo(() => car?.specs.filter(spec => category === "All systems" || spec.category === category) ?? [], [car, category]);
  if (isLoading) return <AutoVistaLayout><div className="mx-auto max-w-[1440px] px-5 py-24 lg:px-10"><div className="h-[520px] animate-pulse rounded-[28px] bg-white/[0.05]" /></div></AutoVistaLayout>;
  if (!car) return <AutoVistaLayout><div className="mx-auto max-w-[1440px] px-5 py-32 text-center"><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#c8f06a]">404 / not in the archive</div><h1 className="mt-4 font-display text-5xl font-semibold tracking-[-0.06em] text-white">Machine not found.</h1><Link href="/cars" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#c8f06a] px-5 py-3 text-sm font-semibold text-[#0b0d0e]">Return to archive <ArrowUpRight size={15} /></Link></div></AutoVistaLayout>;
  const addCompare = () => { const next = compare.includes(car.slug) ? compare.filter(item => item !== car.slug) : compare.length < 3 ? [...compare, car.slug] : compare; setCompare(next); localStorage.setItem("autovista-compare", JSON.stringify(next)); };
  const share = async () => { try { await navigator.clipboard?.writeText(window.location.href); } catch { /* clipboard unavailable */ } };
  return <AutoVistaLayout>
    <div className="mx-auto max-w-[1440px] px-5 py-8 lg:px-10 lg:py-12"><div className="mb-8 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.16em] text-white/30"><Link href="/cars" className="flex items-center gap-2 transition hover:text-white"><ArrowLeft size={13} /> Archive</Link><ChevronRight size={12} /><span>{car.make}</span><ChevronRight size={12} /><span className="text-white/55">{car.model}</span></div>
      <section className="grid gap-8 lg:grid-cols-[1.06fr_0.94fr] lg:items-end"><div className="relative min-h-[430px] overflow-hidden rounded-[28px] border border-white/[0.09] bg-[#151a1a]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_45%_45%,rgba(200,240,106,0.12),transparent_37%)]" /><div className="absolute left-7 top-7 z-10 font-mono text-[10px] uppercase tracking-[0.18em] text-[#c8f06a]">{car.generation} / {car.year} / {car.bodyStyle}</div><img src={car.heroImageUrl} alt={`${car.make} ${car.model}`} className="absolute inset-0 h-full w-full object-cover opacity-70 mix-blend-screen" /><div className="absolute inset-0 bg-gradient-to-t from-[#151a1a] via-transparent to-[#151a1a]/10" /><div className="absolute bottom-7 left-7 right-7 z-10 flex items-end justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[0.2em] text-white/45">{car.make}</div><h1 className="mt-1 font-display text-6xl font-semibold leading-[0.82] tracking-[-0.075em] text-white md:text-8xl">{car.model}</h1></div><span className="font-mono text-xs uppercase tracking-[0.16em] text-white/40">{car.trim}</span></div></div><div className="pb-2"><div className="mb-5 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.22em] text-[#c8f06a]"><Sparkles size={13} /> Vehicle dossier</div><h2 className="max-w-xl font-display text-4xl font-semibold leading-[0.95] tracking-[-0.06em] text-white md:text-6xl">The complete<br /><span className="text-white/35">{car.make} {car.model}.</span></h2><p className="mt-6 max-w-lg text-base leading-7 text-white/50">{car.summary}</p><div className="mt-8 flex flex-wrap gap-2"><button onClick={() => { if (!isAuthenticated) { window.location.href = "/api/oauth/login"; return; } toggleFavorite.mutate({ trimId: car.id }, { onSuccess: result => setSaved(result.saved) }); }} className={`flex items-center gap-2 rounded-full border px-4 py-2.5 text-xs transition ${saved ? "border-[#c8f06a]/60 bg-[#c8f06a]/10 text-[#c8f06a]" : "border-white/15 text-white/65 hover:border-white/30 hover:text-white"}`}><Bookmark size={14} fill={saved ? "currentColor" : "none"} /> {saved ? "Saved to archive" : "Save vehicle"}</button><button onClick={addCompare} className={`flex items-center gap-2 rounded-full border px-4 py-2.5 text-xs transition ${compare.includes(car.slug) ? "border-[#c8f06a]/60 bg-[#c8f06a]/10 text-[#c8f06a]" : "border-white/15 text-white/65 hover:border-white/30 hover:text-white"}`}><GitCompareArrows size={14} /> {compare.includes(car.slug) ? "In compare" : "Add to compare"}</button><button onClick={share} className="flex items-center gap-2 rounded-full border border-white/15 px-4 py-2.5 text-xs text-white/65 transition hover:border-white/30 hover:text-white"><Share2 size={14} /> Share</button></div></div></section>
      <section className="mt-12 grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-white/[0.08] bg-white/[0.08] md:grid-cols-4"><Metric value={car.horsepower.toLocaleString()} label="horsepower" unit="hp" /><Metric value={car.zeroToSixty} label="0–60 mph" /><Metric value={car.topSpeedKph.toLocaleString()} label="top speed" unit="km/h" /><Metric value={car.rangeKm ? car.rangeKm.toLocaleString() : "—"} label={car.rangeKm ? "electric range" : "range data"} unit={car.rangeKm ? "km" : undefined} /></section>
      <div className="mt-20"><div className="mb-7 flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><div className="mb-3 font-mono text-[10px] uppercase tracking-[0.2em] text-[#c8f06a]">Technical layer / 02</div><h2 className="font-display text-4xl font-semibold tracking-[-0.06em] text-white md:text-5xl">See what moves it.</h2></div><p className="max-w-sm text-sm leading-6 text-white/40">Drag to orbit the assembly. Move the slider to separate the systems. Click a node to isolate its purpose.</p></div>{car.has3d ? <ExplodedViewer car={car} /> : <div className="rounded-[24px] border border-dashed border-white/15 bg-[#111516] p-8 text-center"><div className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#c8f06a]">3D asset pending</div><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-white/40">This dossier is using a verified {car.make} {car.model} image and specification set. A matching {car.make} {car.model} GLB asset will be added before the interactive explorer is enabled for this model.</p></div>}</div>
      <section className="mt-20 grid gap-12 lg:grid-cols-[0.7fr_1.3fr]"><div><div className="mb-3 font-mono text-[10px] uppercase tracking-[0.2em] text-[#c8f06a]">Specification sheet / 03</div><h2 className="font-display text-4xl font-semibold tracking-[-0.06em] text-white md:text-5xl">The numbers<br /><span className="text-white/35">behind the feeling.</span></h2><div className="mt-8 flex flex-wrap gap-2">{categories.map(item => <button key={item} onClick={() => setCategory(item)} className={`rounded-full border px-3 py-2 font-mono text-[9px] uppercase tracking-[0.14em] transition ${category === item ? "border-[#c8f06a]/60 bg-[#c8f06a]/10 text-[#c8f06a]" : "border-white/10 text-white/35 hover:border-white/25 hover:text-white"}`}>{item}</button>)}</div></div><div className="grid gap-3 sm:grid-cols-2">{filteredSpecs.length ? filteredSpecs.map((spec, index) => <div key={`${spec.key}-${index}`} className="rounded-2xl border border-white/[0.09] bg-[#111516] p-5"><div className="font-mono text-[9px] uppercase tracking-[0.16em] text-white/30">{spec.category}</div><div className="mt-6 flex items-end justify-between gap-4"><div className="text-sm text-white/60">{spec.key}</div><div className="text-right font-display text-2xl font-semibold tracking-[-0.04em] text-white">{spec.value}<span className="ml-1 font-mono text-[9px] uppercase tracking-[0.1em] text-[#c8f06a]">{spec.unit ?? ""}</span></div></div></div>) : <div className="col-span-2 rounded-2xl border border-dashed border-white/15 p-8 text-sm text-white/35">No specifications have been published for this system yet.</div>}</div></section>
      <section className="mt-20 grid gap-8 lg:grid-cols-[1fr_0.65fr]"><div className="rounded-[24px] border border-white/[0.09] bg-[#111516] p-6 md:p-8"><div className="flex items-start justify-between"><div><div className="mb-3 font-mono text-[10px] uppercase tracking-[0.2em] text-[#c8f06a]">Powertrain architecture</div><h2 className="font-display text-3xl font-semibold tracking-[-0.05em] text-white">{car.powertrain}</h2></div><Info size={19} className="text-[#c8f06a]" /></div><div className="mt-8 grid gap-3 sm:grid-cols-3"><DataPoint label="Drivetrain" value={car.drivetrain} /><DataPoint label="Transmission" value={car.transmission} /><DataPoint label="Efficiency" value={car.efficiency} /></div></div><div className="rounded-[24px] border border-[#c8f06a]/20 bg-[#c8f06a]/[0.06] p-6 md:p-8"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.2em] text-[#c8f06a]"><CircleAlert size={14} /> Source note</div><p className="mt-5 text-sm leading-6 text-white/55">Values are a reference snapshot for the listed model year and market. Confirm local configuration before making a purchase decision.</p><div className="mt-6 space-y-2">{car.sources.map(source => <a key={source.url} href={source.url} target="_blank" rel="noreferrer" className="flex items-center justify-between border-t border-white/10 pt-3 text-xs text-white/55 hover:text-white"><span>{source.publisher}{source.date ? ` · ${source.date}` : ""}</span><ExternalLink size={13} /></a>)}</div></div></section>
      {related.length > 0 && <section className="mt-20 border-t border-white/[0.09] pt-16"><div className="flex items-end justify-between"><div><div className="mb-3 font-mono text-[10px] uppercase tracking-[0.2em] text-[#c8f06a]">Continue the field</div><h2 className="font-display text-4xl font-semibold tracking-[-0.06em] text-white">Machines in the same<br /><span className="text-white/35">conversation.</span></h2></div><Link href="/cars" className="hidden items-center gap-2 font-mono text-[10px] uppercase tracking-[0.16em] text-white/45 hover:text-[#c8f06a] sm:flex">All vehicles <ArrowUpRight size={14} /></Link></div><div className="mt-10 grid gap-5 md:grid-cols-3">{related.map(item => <VehicleCard key={item.slug} car={item} />)}</div></section>}
    </div>
  </AutoVistaLayout>;
}

function Metric({ value, label, unit }: { value: string; label: string; unit?: string }) { return <div className="bg-[#111516] p-5 md:p-6"><div className="font-display text-3xl font-semibold tracking-[-0.06em] text-white md:text-4xl">{value}<span className="ml-1 font-mono text-[9px] uppercase tracking-[0.1em] text-[#c8f06a]">{unit}</span></div><div className="mt-2 font-mono text-[9px] uppercase tracking-[0.16em] text-white/30">{label}</div></div>; }
function DataPoint({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/[0.08] bg-black/10 p-4"><div className="font-mono text-[9px] uppercase tracking-[0.14em] text-white/30">{label}</div><div className="mt-3 text-sm text-white/75">{value}</div></div>; }
