import { ArrowUpRight, Bookmark, Gauge, GitCompareArrows } from "lucide-react";
import { Link } from "wouter";
import type { CatalogCar } from "../../../server/catalog";

export function VehicleCard({ car, selectedForCompare, onCompare, onSave }: { car: CatalogCar; selectedForCompare?: boolean; onCompare?: () => void; onSave?: () => void }) {
  return <article className="group overflow-hidden rounded-[22px] border border-white/[0.09] bg-[#131718] transition duration-300 hover:-translate-y-1 hover:border-white/20 hover:bg-[#171c1d]">
    <Link href={`/cars/${car.slug}`} className="block">
      <div className="relative aspect-[1.36] overflow-hidden bg-[#1b2020]">
        <img src={car.heroImageUrl} alt={`${car.make} ${car.model} ${car.trim}`} className="h-full w-full object-cover opacity-80 mix-blend-screen transition duration-700 group-hover:scale-105 group-hover:opacity-95" />
        <div className="absolute inset-0 bg-gradient-to-t from-[#131718] via-transparent to-black/20" />
        <div className="absolute left-4 top-4 flex items-center gap-2"><span className="rounded-full bg-[#c8f06a] px-2.5 py-1 font-mono text-[9px] font-bold uppercase tracking-[0.12em] text-[#0b0d0e]">{car.year}</span><span className="rounded-full border border-white/15 bg-[#0b0d0e]/40 px-2.5 py-1 font-mono text-[9px] uppercase tracking-[0.12em] text-white/70 backdrop-blur">{car.bodyStyle}</span></div>
        <div className="absolute bottom-4 left-4 right-4 flex items-end justify-between"><div><div className="font-mono text-[10px] uppercase tracking-[0.18em] text-white/50">{car.make}</div><h3 className="mt-1 font-display text-2xl font-semibold tracking-[-0.05em] text-white">{car.model}</h3></div><ArrowUpRight size={18} className="text-white/50 transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5 group-hover:text-[#c8f06a]" /></div>
      </div>
    </Link>
    <div className="p-4"><div className="mb-4 text-xs text-white/40">{car.trim} · {car.fuelType}</div><div className="grid grid-cols-3 divide-x divide-white/[0.08] border-y border-white/[0.08] py-3"><div className="pr-3"><div className="font-display text-lg font-semibold text-white">{car.horsepower.toLocaleString()}</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[0.12em] text-white/30">hp</div></div><div className="px-3"><div className="font-display text-lg font-semibold text-white">{car.zeroToSixty}</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[0.12em] text-white/30">0–60</div></div><div className="pl-3"><div className="font-display text-lg font-semibold text-white">{car.topSpeedKph}</div><div className="mt-1 font-mono text-[9px] uppercase tracking-[0.12em] text-white/30">km/h</div></div></div><div className="mt-4 flex items-center justify-between"><span className="flex items-center gap-1.5 font-mono text-[10px] uppercase tracking-[0.12em] text-white/35"><Gauge size={12} className="text-[#c8f06a]" /> {car.drivetrain}</span><div className="flex items-center gap-1.5"><button aria-label={`Save ${car.make} ${car.model}`} onClick={event => { event.preventDefault(); onSave?.(); }} className="flex h-8 w-8 items-center justify-center rounded-full border border-white/10 text-white/45 transition hover:border-[#c8f06a]/50 hover:text-[#c8f06a]"><Bookmark size={14} /></button><button aria-label={`Compare ${car.make} ${car.model}`} onClick={event => { event.preventDefault(); onCompare?.(); }} className={`flex h-8 items-center gap-1.5 rounded-full border px-2.5 font-mono text-[9px] uppercase tracking-[0.1em] transition ${selectedForCompare ? "border-[#c8f06a]/60 bg-[#c8f06a]/10 text-[#c8f06a]" : "border-white/10 text-white/45 hover:border-[#c8f06a]/50 hover:text-[#c8f06a]"}`}><GitCompareArrows size={13} /> {selectedForCompare ? "Added" : "Compare"}</button></div></div></div>
  </article>;
}
