import { ArrowUpRight, Bookmark, LogIn, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { AutoVistaLayout } from "@/components/AutoVistaLayout";
import { VehicleCard } from "@/components/VehicleCard";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";

export default function Favorites() {
  const { user, isAuthenticated, loading } = useAuth();
  const { data: favorites, isLoading } = trpc.favorites.list.useQuery(undefined, { enabled: isAuthenticated });
  return <AutoVistaLayout><div className="mx-auto max-w-[1440px] px-5 py-14 lg:px-10 lg:py-20"><div className="flex flex-col justify-between gap-7 border-b border-white/[0.09] pb-10 md:flex-row md:items-end"><div><div className="mb-4 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.22em] text-[#c8f06a]"><Bookmark size={13} /> Personal archive / 04</div><h1 className="font-display text-6xl font-semibold leading-[0.86] tracking-[-0.075em] text-white md:text-8xl">Your<br /><span className="text-white/35">machines.</span></h1></div><p className="max-w-sm text-base leading-7 text-white/45">Keep the cars you return to close. Your saved archive stays private to your account.</p></div>{loading || isLoading ? <div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><div className="h-80 animate-pulse rounded-[22px] bg-white/[0.05]" /><div className="h-80 animate-pulse rounded-[22px] bg-white/[0.05]" /></div> : !isAuthenticated ? <div className="mt-12 rounded-[28px] border border-dashed border-white/15 bg-[#111516] px-6 py-20 text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full border border-[#c8f06a]/30 bg-[#c8f06a]/10 text-[#c8f06a]"><LogIn size={24} /></div><h2 className="mt-6 font-display text-3xl font-semibold tracking-[-0.05em] text-white">Sign in to keep a shortlist.</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-white/40">Save vehicles from the archive and come back when the next detail is worth another look.</p><button onClick={() => startLogin()} className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#c8f06a] px-5 py-3 text-sm font-semibold text-[#0b0d0e]">Sign in <ArrowUpRight size={15} /></button></div> : favorites?.length ? <div className="mt-12"><div className="mb-5 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.16em] text-white/30"><Sparkles size={13} className="text-[#c8f06a]" /> {favorites.length} saved machines</div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{favorites.map(car => car && <VehicleCard key={car.slug} car={car} />)}</div></div> : <div className="mt-12 rounded-[28px] border border-dashed border-white/15 bg-[#111516] px-6 py-20 text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full border border-white/15 text-white/35"><Bookmark size={24} /></div><h2 className="mt-6 font-display text-3xl font-semibold tracking-[-0.05em] text-white">Nothing saved yet.</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-white/40">Start with the archive and save the vehicles that keep your curiosity running.</p><Link href="/cars" className="mt-7 inline-flex items-center gap-2 rounded-full border border-white/15 px-5 py-3 text-sm text-white/65 hover:border-white/30 hover:text-white">Explore vehicles <ArrowUpRight size={15} /></Link></div>}</div></AutoVistaLayout>;
}
