import { ArrowUpRight, Building2, Globe2, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { AutoVistaLayout } from "@/components/AutoVistaLayout";
import { trpc } from "@/lib/trpc";

export default function Makes() {
  const { data: makes, isLoading } = trpc.catalog.makes.useQuery();
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => makes?.filter(make => make.name.toLowerCase().includes(query.toLowerCase())) ?? [], [makes, query]);
  return <AutoVistaLayout><div className="mx-auto max-w-[1440px] px-5 py-14 lg:px-10 lg:py-20"><div className="flex flex-col justify-between gap-8 border-b border-white/[0.09] pb-10 lg:flex-row lg:items-end"><div><div className="mb-5 flex items-center gap-3 font-mono text-[10px] uppercase tracking-[0.22em] text-[#c8f06a]"><Building2 size={13} /> The directory / 02</div><h1 className="font-display text-6xl font-semibold leading-[0.86] tracking-[-0.075em] text-white md:text-8xl">Every<br /><span className="text-white/35">maker.</span></h1></div><div className="max-w-sm"><p className="text-base leading-7 text-white/45">From family hatchbacks to homologation specials, follow the names behind the machines.</p><div className="mt-5 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.16em] text-white/30"><Globe2 size={13} className="text-[#c8f06a]" /> Global manufacturers index</div></div></div><div className="relative mt-10 max-w-xl"><Search size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-white/35" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search manufacturers..." className="h-14 w-full rounded-2xl border border-white/10 bg-[#111516] pl-12 text-sm text-white outline-none placeholder:text-white/25 focus:border-[#c8f06a]/60" /></div><div className="mt-12"><div className="mb-5 font-mono text-[10px] uppercase tracking-[0.18em] text-white/30">{isLoading ? "Loading directory..." : `${filtered.length} indexed makes`}</div>{isLoading ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{Array.from({ length: 8 }).map((_, index) => <div key={index} className="h-36 animate-pulse rounded-2xl bg-white/[0.05]" />)}</div> : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{filtered.map((make, index) => <Link key={make.slug} href={`/cars?make=${make.slug}`} className="group flex min-h-[150px] flex-col justify-between rounded-2xl border border-white/[0.09] bg-[#111516] p-5 transition hover:-translate-y-1 hover:border-[#c8f06a]/45"><div className="flex items-start justify-between"><span className="font-mono text-[10px] text-white/25">{String(index + 1).padStart(2, "0")}</span><ArrowUpRight size={16} className="text-white/25 transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-[#c8f06a]" /></div><div><h2 className="font-display text-2xl font-semibold tracking-[-0.05em] text-white">{make.name}</h2><div className="mt-2 text-xs text-white/35">View models <span className="text-[#c8f06a]">→</span></div></div></Link>)}</div>}{!isLoading && filtered.length === 0 && <div className="rounded-2xl border border-dashed border-white/15 p-12 text-center text-sm text-white/40">No manufacturer matches that search.</div>}</div></div></AutoVistaLayout>;
}
